foreground #f8f8f2
background #272822
selection_foreground #272822
selection_background #f8f8f2
cursor #f8f8f2
cursor_text_color #272822
url_color #66d9ef

active_tab_foreground #272822
active_tab_background #66d9ef
inactive_tab_foreground #f8f8f2
inactive_tab_background #383830

active_border_color #66d9ef
inactive_border_color #75715e
bell_border_color #f4bf75

wayland_titlebar_color #272822

color0  #49483e
color1  #f92672
color2  #a6e22e
color3  #f4bf75
color4  #66d9ef
color5  #ae81ff
color6  #a1efe4
color7  #f5f4f1
color8  #75715e
color9  #f92672
color10 #a6e22e
color11 #f4bf75
color12 #66d9ef
color13 #ae81ff
color14 #a1efe4
color15 #a59f85

mark1_foreground #272822
mark1_background #66d9ef
mark2_foreground #272822
mark2_background #ae81ff
mark3_foreground #272822
mark3_background #a1efe4
