foreground #cad3f5
background #24273a
selection_foreground #24273a
selection_background #cad3f5
cursor #cad3f5
cursor_text_color #24273a
url_color #8aadf4

active_tab_foreground #24273a
active_tab_background #8aadf4
inactive_tab_foreground #cad3f5
inactive_tab_background #1e2030

active_border_color #8aadf4
inactive_border_color #494d64
bell_border_color #eed49f

wayland_titlebar_color #24273a

color0  #363a4f
color1  #ed8796
color2  #a6da95
color3  #eed49f
color4  #8aadf4
color5  #c6a0f6
color6  #8bd5ca
color7  #f4dbd6
color8  #494d64
color9  #ed8796
color10 #a6da95
color11 #eed49f
color12 #8aadf4
color13 #c6a0f6
color14 #8bd5ca
color15 #5b6078

mark1_foreground #24273a
mark1_background #8aadf4
mark2_foreground #24273a
mark2_background #c6a0f6
mark3_foreground #24273a
mark3_background #8bd5ca
