foreground #B279A7
background #191919
selection_foreground #191919
selection_background #B279A7
cursor #B279A7
cursor_text_color #191919
url_color #CF86C1

active_tab_foreground #191919
active_tab_background #CF86C1
inactive_tab_foreground #B279A7
inactive_tab_background #DE6E7C

active_border_color #CF86C1
inactive_border_color #B77E64
bell_border_color #8BAE68

wayland_titlebar_color #191919

color0  #819B69
color1  #3D3839
color2  #D68C67
color3  #8BAE68
color4  #CF86C1
color5  #65B8C1
color6  #61ABDA
color7  #66A5AD
color8  #B77E64
color9  #3D3839
color10 #D68C67
color11 #8BAE68
color12 #CF86C1
color13 #65B8C1
color14 #61ABDA
color15 #6099C0

mark1_foreground #191919
mark1_background #CF86C1
mark2_foreground #191919
mark2_background #65B8C1
mark3_foreground #191919
mark3_background #61ABDA
